export default {
  brian: [
    `As managing member for Guaranty Solutions, LLC (guarantysolutions.com), Mr. Evans is responsible for the company’s overall strategic direction, investment policy and operations.  Guaranty Solutions, LLC (GS) is a private equity information firm and premier asset recovery agency based in the greater Phoenix area.  GS has made a focused effort to be the premier judgment/deficiency recovery firm for institutions.  GS has developed proprietary software/database for institutions to manage all judgment recovery aspects.  Mr. Evans also owns Universal Equity Group, a private equity firm focused on distressed debt and real estate investment opportunities in the western United States.  In 2009, Universal Equity Group participated in real estate/debt related investments with unpaid principal note balances in excess of $1.9 billion dollars.  One transaction receiving national attention involved one of Arizona’s largest private lenders. In June 2009, Universal Equity Group negotiated, structured and closed a bankruptcy exit financing facility for Mortgages Limited, one of the largest bankruptcies in Arizona’s history. The bankruptcy estate consisted of a portfolio of acquisition, development and construction loans with an unpaid principal balance close to $900 million.  Mr. Evans has over 24 year’s experience in real estate and financial advisory services as well as investment and portfolio management.`,
    `Mr. Evans was previously an estate advisor for Morgan Stanley Dean Witter. Prior to Morgan Stanley, Mr. Evans worked for the public accounting firm Culbert, Nowicki & Associates where he provided tax planning and advice for both entities and individuals. Mr. Evans began his career with the global public accounting firm PriceWaterhouseCoopers, LLC (formerly Coopers & Lybrand, LLP) performing audits of publicly traded companies.`,
    `Mr. Evans is a licensed Certified Public Accountant and a licensed real estate broker in Arizona.  Mr. Evans is a board member and former president of the Phoenix chapter Turnaround Management Association (TMA), an international nonprofit association dedicated to corporate renewal and turnaround management.  Mr. Evans is also a member of the American Institute of Certified Public Accountants (AICPA).  Mr. Evans has been quoted in numerous publications including the Phoenix Business Journal and has been a lecturer for programs on various real estate topics.`,
    `Mr. Evans is also a member of several corporate advisory boards and is a founding member of The Coach Jesse Parker Legacy Foundation, a nonprofit focused on rewarding excellent teachers and AZM2M Foundation, a nonprofit focused on supporting an orphanage and building houses in Mexico. Mr. Evans is also on the board of 33 Buckets, a nonprofit focused on providing clean water to developing communities.  He earned his Bachelor of Science Degree in Accountancy from Arizona State University Honors College.`,
  ],
  guy: [
    `As Chief Information Officer for Guaranty Solutions, Guy has been instrumental in the development and creation of our proprietary judgment management system allowing us to identify, analyze and prioritize our client’s judgments to ensure maximum portfolio collection returns.`,
    `Prior to joining Guaranty Solutions, Guy spent 16 years with a leading global provider of world-class content, information analytics and workflow solutions for professionals in the legal, risk management, corporate, government, law enforcement, accounting and academic markets. Millions of customers in more than 100 countries on six continents use this service to achieve and outperform their goals, including the 100 largest law firms in the U.S. and 95% of Fortune 500 companies.`,
    `Guy spent years training hundreds of attorneys and other legal professionals in these organizations how to uncover background information on expert witnesses, parties in litigation, missing person location, etc.`,
    `Guy now uses the same skills and methods on behalf of Guaranty Solutions to obtain critical background information on debtors, including discovery of additional assets owned by the debtor and possible fraudulent conveyances of real property, information that is vital to the pursuit of creditor remedies.`,
    `Guy received a Bachelor of Science degree from Utah State University and a J.D. from the University of Colorado School of Law.`,
  ],
  sam: [
    `Sam has accumulated over 10 years of experience in the Financial Services industries.  Through the use of data analytics, Sam has been successful in completing multiple projects to improve business and process efficiency for several organizations.`,
    `As Director of Research, Sam ensures that Guaranty Solutions utilizes the most accurate data to help analyze its debtors.  Sam leads a team of researchers that specialize in asset discovery.  Sam directs research strategies and has helped analyze Guaranty Solutions' propriety debtor scoring model.  Sam specializes in taking information and transforming it to create effective collection strategies.`,
    `Sam graduated from Arizona State University with a BS in Accounting.`,
  ],
  dustin: [
    `Mr. Horne has more than 20 years of experience in the practice of law.  More specifically, he began his career as an estate planning/corporate/tax attorney with a Phoenix-based law firm.  He has been the lead counsel on several multi-million dollar mergers/acquisitions and acted as a legal advisor to numerous large corporations. Mr. Horne has also been involved in asset protection strategies (both domestic and offshore), formation and managing foreign captive insurance companies, as well as asset recovery in Arizona.  He has been a preferred guest on a local estate planning radio show and has also been a speaker for multiple estate planning seminars.`,
    `Mr. Horne received a Bachelor of Science degree in Accounting from Arizona State University and a J.D. from California Western School of Law.  In addition to being a practicing attorney, Mr. Horne is a licensed CPA (Certified Public Accountant) in the State of Arizona.`,
    `As the General Counsel and CFO, Mr. Horne is responsible for all of the general legal strategies, financial transactions and projections, corporate tax returns, and human resources issues.`,
    `Mr. Horne is actively involved in charitable organizations, especially those dealing with autistic children.`,
  ],
  johnathan: [
    `Johnathan joined Guaranty Solutions in July of 2018. As an Associate, his responsibilities focus on asset management & strategic collection analysis as well as providing support on company projects. Johnathan also assists in acquisitions and business development all while maintaining strong communication with clients, partners, and the internal team.`,
    `Johnathan is also involved in two local foundations/committees. These include holding a position as a committee member for the Phoenix chapter of the Turnaround Management Association (TMA) as well as being a board member on the AZM2M Foundation that builds homes for the less fortunate in Francisco Murgia, Baja, Mexico.`,
  ],
}
